name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust nightly
        run: rustup toolchain install nightly-2025-03-08 --component rustfmt --component clippy
      - name: Run tests
        run: cargo +nightly-2025-03-08 test --all-targets --all-features
        env:
          RUST_LOG: debug
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust nightly
        run: rustup toolchain install nightly-2025-03-08 --component rustfmt
      - name: Check formatting
        run: cargo +nightly-2025-03-08 fmt -- --check
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust nightly
        run: rustup toolchain install nightly-2025-03-08 --component clippy
      - name: Run clippy
        run: cargo +nightly-2025-03-08 clippy --all-targets --all-features -- -D warnings
  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust nightly
        run: rustup toolchain install nightly-2025-03-08
      - name: Generate documentation
        env:
          RUSTDOCFLAGS: -D warnings
        run: cargo +nightly-2025-03-08 doc --no-deps
      - name: Run doc tests
        run: cargo +nightly-2025-03-08 test --doc
